//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFIDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.contact_methods = new HashSet<contact_methods>();
            this.credit_applications = new HashSet<credit_applications>();
            this.credits = new HashSet<credit>();
            this.personal_references = new HashSet<personal_references>();
        }
    
        public string rfc { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string last_name { get; set; }
        public string curp { get; set; }
        public System.DateTime birthdate { get; set; }
        public int id_address { get; set; }
        public int id_work_center { get; set; }
        public string card_number { get; set; }
    
        public virtual address address { get; set; }
        public virtual bank_accounts bank_accounts { get; set; }
        public virtual work_centers work_centers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact_methods> contact_methods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<credit_applications> credit_applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<credit> credits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personal_references> personal_references { get; set; }
    }
}
