//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFIDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_methods
    {
        public int id_contact_method { get; set; }
        public string value { get; set; }
        public int id_contact_method_type { get; set; }
        public string client_rfc { get; set; }
        public string ine_key { get; set; }
    
        public virtual client client { get; set; }
        public virtual contact_method_types contact_method_types { get; set; }
        public virtual personal_references personal_references { get; set; }
    }
}
