//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFIDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit_conditions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public credit_conditions()
        {
            this.credit_applications = new HashSet<credit_applications>();
            this.regimes = new HashSet<regime>();
        }
    
        public double interest_rate { get; set; }
        public bool is_active { get; set; }
        public bool is_iva_applied { get; set; }
        public double interest_on_arrears { get; set; }
        public double advance_payment_reduction { get; set; }
        public int payment_months { get; set; }
        public int id_credit_type { get; set; }
        public string identifier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<credit_applications> credit_applications { get; set; }
        public virtual credit_types credit_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<regime> regimes { get; set; }
    }
}
