//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFIDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class digital_documents
    {
        public int id_digital_document { get; set; }
        public string name { get; set; }
        public string format { get; set; }
        public byte[] contect { get; set; }
        public string credit_application_invoice { get; set; }
    
        public virtual credit_applications credit_applications { get; set; }
    }
}
