//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFIDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payment()
        {
            this.payment_layouts = new HashSet<payment_layouts>();
        }
    
        public int id_payment { get; set; }
        public decimal amount { get; set; }
        public string invoice { get; set; }
        public System.DateTime planned_date { get; set; }
        public string credit_invoice { get; set; }
        public System.DateTime reconciliation_date { get; set; }
    
        public virtual credit credit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_layouts> payment_layouts { get; set; }
    }
}
