//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFIDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class polices_apply_dictums
    {
        public int id_polices_apply_dictums { get; set; }
        public int id_dictum { get; set; }
        public string credit_granting_police_title { get; set; }
        public bool is_applied { get; set; }
    
        public virtual credit_granting_polices credit_granting_polices { get; set; }
        public virtual dictum dictum { get; set; }
    }
}
