//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFIDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SFIDatabaseContext : DbContext
    {
        public SFIDatabaseContext()
            : base("name=SFIDatabaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<bank_accounts> bank_accounts { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<contact_method_types> contact_method_types { get; set; }
        public virtual DbSet<contact_methods> contact_methods { get; set; }
        public virtual DbSet<credit_applications> credit_applications { get; set; }
        public virtual DbSet<credit_applications_state> credit_applications_state { get; set; }
        public virtual DbSet<credit_conditions> credit_conditions { get; set; }
        public virtual DbSet<credit_granting_polices> credit_granting_polices { get; set; }
        public virtual DbSet<credit_types> credit_types { get; set; }
        public virtual DbSet<credit> credits { get; set; }
        public virtual DbSet<dictum> dictums { get; set; }
        public virtual DbSet<digital_documents> digital_documents { get; set; }
        public virtual DbSet<employee_roles> employee_roles { get; set; }
        public virtual DbSet<personal_references> personal_references { get; set; }
        public virtual DbSet<polices_apply_dictums> polices_apply_dictums { get; set; }
        public virtual DbSet<regime> regimes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<system_accounts> system_accounts { get; set; }
        public virtual DbSet<work_centers> work_centers { get; set; }
    }
}
