//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFIClient.SFIService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataTypeExample", Namespace="http://schemas.datacontract.org/2004/07/SFIDataAccess.Model")]
    [System.SerializableAttribute()]
    public partial class DataTypeExample : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsExampleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExample {
            get {
                return this.IsExampleField;
            }
            set {
                if ((this.IsExampleField.Equals(value) != true)) {
                    this.IsExampleField = value;
                    this.RaisePropertyChanged("IsExample");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/SFIDataAccess.CustomExceptions")]
    [System.SerializableAttribute()]
    public partial class ServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/SFIDataAccess.Model")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Card_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Has_active_creditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Has_credit_applicationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_work_centerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RfcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((this.BirthdateField.Equals(value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Card_number {
            get {
                return this.Card_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.Card_numberField, value) != true)) {
                    this.Card_numberField = value;
                    this.RaisePropertyChanged("Card_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Curp {
            get {
                return this.CurpField;
            }
            set {
                if ((object.ReferenceEquals(this.CurpField, value) != true)) {
                    this.CurpField = value;
                    this.RaisePropertyChanged("Curp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Has_active_credit {
            get {
                return this.Has_active_creditField;
            }
            set {
                if ((this.Has_active_creditField.Equals(value) != true)) {
                    this.Has_active_creditField = value;
                    this.RaisePropertyChanged("Has_active_credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Has_credit_application {
            get {
                return this.Has_credit_applicationField;
            }
            set {
                if ((this.Has_credit_applicationField.Equals(value) != true)) {
                    this.Has_credit_applicationField = value;
                    this.RaisePropertyChanged("Has_credit_application");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_address {
            get {
                return this.Id_addressField;
            }
            set {
                if ((this.Id_addressField.Equals(value) != true)) {
                    this.Id_addressField = value;
                    this.RaisePropertyChanged("Id_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_work_center {
            get {
                return this.Id_work_centerField;
            }
            set {
                if ((this.Id_work_centerField.Equals(value) != true)) {
                    this.Id_work_centerField = value;
                    this.RaisePropertyChanged("Id_work_center");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rfc {
            get {
                return this.RfcField;
            }
            set {
                if ((object.ReferenceEquals(this.RfcField, value) != true)) {
                    this.RfcField = value;
                    this.RaisePropertyChanged("Rfc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://schemas.datacontract.org/2004/07/SFIDataAccess.Model")]
    [System.SerializableAttribute()]
    public partial class BankAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Card_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HolderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bank {
            get {
                return this.BankField;
            }
            set {
                if ((object.ReferenceEquals(this.BankField, value) != true)) {
                    this.BankField = value;
                    this.RaisePropertyChanged("Bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Card_number {
            get {
                return this.Card_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.Card_numberField, value) != true)) {
                    this.Card_numberField = value;
                    this.RaisePropertyChanged("Card_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Holder {
            get {
                return this.HolderField;
            }
            set {
                if ((object.ReferenceEquals(this.HolderField, value) != true)) {
                    this.HolderField = value;
                    this.RaisePropertyChanged("Holder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SFIService.IServiceExample")]
    public interface IServiceExample {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExample/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceExample/GetDataUsingDataContractResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SFIClient.SFIService.ServiceFault), Action="http://tempuri.org/IServiceExample/GetDataUsingDataContractServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/SFIDataAccess.CustomExceptions")]
        SFIClient.SFIService.DataTypeExample GetDataUsingDataContract();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExample/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceExample/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<SFIClient.SFIService.DataTypeExample> GetDataUsingDataContractAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceExampleChannel : SFIClient.SFIService.IServiceExample, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceExampleClient : System.ServiceModel.ClientBase<SFIClient.SFIService.IServiceExample>, SFIClient.SFIService.IServiceExample {
        
        public ServiceExampleClient() {
        }
        
        public ServiceExampleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceExampleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExampleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExampleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SFIClient.SFIService.DataTypeExample GetDataUsingDataContract() {
            return base.Channel.GetDataUsingDataContract();
        }
        
        public System.Threading.Tasks.Task<SFIClient.SFIService.DataTypeExample> GetDataUsingDataContractAsync() {
            return base.Channel.GetDataUsingDataContractAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SFIService.IClientsService")]
    public interface IClientsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsService/RecoverClients", ReplyAction="http://tempuri.org/IClientsService/RecoverClientsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SFIClient.SFIService.ServiceFault), Action="http://tempuri.org/IClientsService/RecoverClientsServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/SFIDataAccess.CustomExceptions")]
        SFIClient.SFIService.Client[] RecoverClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsService/RecoverClients", ReplyAction="http://tempuri.org/IClientsService/RecoverClientsResponse")]
        System.Threading.Tasks.Task<SFIClient.SFIService.Client[]> RecoverClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsService/RecoverBankDetails", ReplyAction="http://tempuri.org/IClientsService/RecoverBankDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SFIClient.SFIService.ServiceFault), Action="http://tempuri.org/IClientsService/RecoverBankDetailsServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/SFIDataAccess.CustomExceptions")]
        SFIClient.SFIService.BankAccount RecoverBankDetails(string cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsService/RecoverBankDetails", ReplyAction="http://tempuri.org/IClientsService/RecoverBankDetailsResponse")]
        System.Threading.Tasks.Task<SFIClient.SFIService.BankAccount> RecoverBankDetailsAsync(string cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsService/UpdateBankAccount", ReplyAction="http://tempuri.org/IClientsService/UpdateBankAccountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SFIClient.SFIService.ServiceFault), Action="http://tempuri.org/IClientsService/UpdateBankAccountServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/SFIDataAccess.CustomExceptions")]
        bool UpdateBankAccount(SFIClient.SFIService.BankAccount bankAccount, string cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsService/UpdateBankAccount", ReplyAction="http://tempuri.org/IClientsService/UpdateBankAccountResponse")]
        System.Threading.Tasks.Task<bool> UpdateBankAccountAsync(SFIClient.SFIService.BankAccount bankAccount, string cardNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientsServiceChannel : SFIClient.SFIService.IClientsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientsServiceClient : System.ServiceModel.ClientBase<SFIClient.SFIService.IClientsService>, SFIClient.SFIService.IClientsService {
        
        public ClientsServiceClient() {
        }
        
        public ClientsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SFIClient.SFIService.Client[] RecoverClients() {
            return base.Channel.RecoverClients();
        }
        
        public System.Threading.Tasks.Task<SFIClient.SFIService.Client[]> RecoverClientsAsync() {
            return base.Channel.RecoverClientsAsync();
        }
        
        public SFIClient.SFIService.BankAccount RecoverBankDetails(string cardNumber) {
            return base.Channel.RecoverBankDetails(cardNumber);
        }
        
        public System.Threading.Tasks.Task<SFIClient.SFIService.BankAccount> RecoverBankDetailsAsync(string cardNumber) {
            return base.Channel.RecoverBankDetailsAsync(cardNumber);
        }
        
        public bool UpdateBankAccount(SFIClient.SFIService.BankAccount bankAccount, string cardNumber) {
            return base.Channel.UpdateBankAccount(bankAccount, cardNumber);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateBankAccountAsync(SFIClient.SFIService.BankAccount bankAccount, string cardNumber) {
            return base.Channel.UpdateBankAccountAsync(bankAccount, cardNumber);
        }
    }
}
