//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFIClient.SFIServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataTypeExample", Namespace="http://schemas.datacontract.org/2004/07/SFIDataAccess.Model")]
    [System.SerializableAttribute()]
    public partial class DataTypeExample : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsExampleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExample {
            get {
                return this.IsExampleField;
            }
            set {
                if ((this.IsExampleField.Equals(value) != true)) {
                    this.IsExampleField = value;
                    this.RaisePropertyChanged("IsExample");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SFIServices.IServiceExample")]
    public interface IServiceExample {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExample/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceExample/GetDataUsingDataContractResponse")]
        SFIClient.SFIServices.DataTypeExample GetDataUsingDataContract();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExample/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceExample/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<SFIClient.SFIServices.DataTypeExample> GetDataUsingDataContractAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceExampleChannel : SFIClient.SFIServices.IServiceExample, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceExampleClient : System.ServiceModel.ClientBase<SFIClient.SFIServices.IServiceExample>, SFIClient.SFIServices.IServiceExample {
        
        public ServiceExampleClient() {
        }
        
        public ServiceExampleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceExampleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExampleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExampleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SFIClient.SFIServices.DataTypeExample GetDataUsingDataContract() {
            return base.Channel.GetDataUsingDataContract();
        }
        
        public System.Threading.Tasks.Task<SFIClient.SFIServices.DataTypeExample> GetDataUsingDataContractAsync() {
            return base.Channel.GetDataUsingDataContractAsync();
        }
    }
}
